# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get the version
        run: |
          echo "ref_name=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV
      - name: Print version
        run: |
          echo "${{ env.ref_name }}"
      - uses: actions/checkout@v2
      - id: getVersion
        uses: battila7/get-version-action@v2
      - uses: actions/github-script@v3
        id: getPackageName
        with:
          result-encoding: string
          script: |
            const getPackageName = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/lib/get_package_name.js`)
            const packageName = getPackageName(`${{ steps.getVersion.outputs.version }}`)
            console.log('package name:', packageName)
            return packageName
      - run: |
          echo "package name: ${{ steps.getPackageName.outputs.result }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install rush
        run: node common/scripts/install-run-rush.js install
      - run: rush install --no-link
      - run: rush link
      - run: rush install
      - run: rush build -t ${{ steps.getPackageName.outputs.result }}
      - run: rush deploy -p ${{ steps.getPackageName.outputs.result }}
      
          
